# Module Title:         Network Systems and Administration
# Module Code:          B9IS121
# Module Instructor:    Kingsley Ibomo
# Assessment Title:     Automated Container Deployment and Administration in the Cloud
# Assessment Number:    1
# Assessment Type:      Practical
# Assessment Weighting: 60%
# Assessment Due Date:  Sunday, 9 November 2025, 8:36 AM
# Student Name:         Mateus Fonseca Campos
# Student ID:           20095949
# Student Email:        20095949@mydbs.ie
# GitHub Repo:          https://github.com/20095949-mateus-campos/networking-ca1

# This file belongs to Part 2: Configuration Management

# Defines parameters to allow Ansible to SSH into the web server
web_servers:  
  hosts:
    aws_ec2:
      # instance public IPv4 address is autofilled by Terraform upon deployment
      ansible_host: 3.253.97.88
      ansible_connection: ssh
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../net_ca1_key.pem
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no" # don't ask to accept key
