name: CI/CD â€“ Dockerized Flask App

on:
  push:
    branches: [ "master" ]

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    
    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: "{{defaultContext}}:flask"
        file: Dockerfile
        push: true
        platforms: linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

  pull:
    name: Pull and run Docker Image
    runs-on: self-hosted
    needs: build-push
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull image
      run: sudo docker compose pull

    - name: Run image
      run: |
        sudo docker stop $(sudo docker ps -a -q) || true
        sudo docker system prune -f
        sudo docker compose up -d
